wallpaper {
  monitor = DP-2
  path = ~/Pictures/Wallpapers/2-cat-waves-mocha.png
  fit_mode = cover
}

wallpaper {
  monitor = HDMI-A-1
  path = ~/Pictures/Wallpapers/bg5.png
  fit_mode = cover
}

splash = false
