hl.on("hyprland.start", function()
	hl.exec_cmd("hyprpaper &")
	hl.exec_cmd("swww-daemon")
	hl.exec_cmd("waybar &")
	hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("mako")
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
	hl.exec_cmd("swayosd-server")
	hl.exec_cmd("kitty")
end)
