# background #061115
background #0d181c
foreground #d9d7d6
selection_background #6791c9
selection_foreground #061115
cursor_text_color #061115
url_color #79aaeb

# Cursor
# uncomment for reverse background
# cursor none
cursor #d9d7d6

# normal
color0 #061115
color1 #df5b61
color2 #78b892
color3 #ecd28b
color4 #6791c9
color5 #c488ec
color6 #67afc1
color7 #d9d7d6

# bright
color8 #313c40
color9 #f16269
color10 #8cd7aa
color11 #f6dc95
color12 #79aaeb
color13 #bc83e3
color14 #7acfe3
color15 #edebea
