set -g status-bg                          "#0a1519"
set -gq @thm_bar_bg                       "#0a1519"

set -gq @thm_bg                           "#0d181c"
set -gq @thm_fg                           "#d9d7d6"
set -gq @thm_primary                      "#78b892"
set -gq @thm_inverse_primary              "#1c272b"
set -gq @thm_surface_low                  "#131e22"
set -gq @thm_surface                      "#1c272b"
set -gq @thm_surface_variant              "#242f33"
set -gq @thm_outline                      "#455054"
set -gq @thm_text_variant                 "#b8b5b4"
