set -g status-bg                          "#1c1f26"
set -gq @thm_bar_bg                       "#1c1f26"
set -gq @thm_bg                           "#1e222a"
set -gq @thm_fg                           "#d9dce3"
set -gq @thm_primary                      "#99c1f1"
set -gq @thm_inverse_primary              "#333a47"
set -gq @thm_surface_low                  "#242932"
set -gq @thm_surface                      "#333a47"
set -gq @thm_surface_variant              "#3a4150"
set -gq @thm_outline                      "#464f62"
set -gq @thm_text_variant                 "#929cb0"
