set -g default-terminal "tmux-256color" # Set terminal type for 256-color support
set -ga terminal-overrides ",*256col*:Tc" # Override to enable true-color for compatible terminals

# set-option -g default-command "exec bash -l"
set-option -g default-shell /usr/bin/zsh

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on # Automatically renumber windows when one is closed,
set -g status-interval 5 # Update the status bar every 5 seconds (default 15)

# General
set -g set-clipboard on         # Use system clipboard
set -g detach-on-destroy off    # Don't exit from tmux when closing a session
set -g escape-time 0            # Remove delay for exiting insert mode with ESC in Neovim
set -g mouse on                 # Enable mouse support
set -g mode-keys vi

# Refresh tmux config with r
unbind r
# bind r source-file ~/.config/tmux/tmux.conf :; display-message "tmux.config reloaded"
bind r source-file ~/.config/tmux/tmux.conf

# Set prefix key
unbind C-b              # Unbind the default prefix key
set -g prefix C-Space   # Set new prefix key to Ctrl+Space

# History limit
set -g history-limit 100000

# Title
set -g set-titles on
set -g set-titles-string "#{pane_title}"

# New window in same path
bind c new-window -c "#{pane_current_path}"

# Split horizontally in CWD 
bind '"' split-window -h -c "#{pane_current_path}"

# Split vertically in CWD
bind % split-window -v -c "#{pane_current_path}"

set -s focus-events on
set -s extended-keys on
set -s escape-time 0

# Switch Windows
unbind n
unbind p
bind h previous-window
bind l next-window

# Maximize pane
unbind m
bind -r m resize-pane -Z

# Popup window
bind C-y display-popup \
  -d "#{pane_current_path}" \
  -w 80% \
  -h 80% \

##
# Styling
##

RED="#f38ba8"
GREEN="#a6e3a1"
YELLOW="#f9e2af"
BLUE="#89b4fa"
MAGENTA="#f5c2e7"
CYAN="#74c7ec"
MAUVE="#cba6f7"
GRAY="#45475a"
DARK_GRAY="#313244"
LIGHT_GRAY="#9399b2"
BLACK="#11111b"
BG="#181825"
FG="#cdd6f4"

# Nerdfont characters
HALF_ROUND_OPEN="#(printf '\uE0B6')"
HALF_ROUND_CLOSE="#(printf '\uE0B4')"
TRIANGLE_OPEN="#(printf '\uE0B2')"
TRIANGLE_CLOSE="#(printf '\uE0B0')"
LINUX="#(printf '\ue712')"

# Uncomment to move statusbar to the top
set-option -g status-position top

# Basic colors of the Statusbar
set-option -g status-style bg=${BG},fg=${FG}

# Show the window list centered between the left and the right section
set-option -g status-justify centre

# Style and set contents on the left section
set-option -g status-left "\
#[bg=default,fg=${FG}] #S \
"

# Style and set contents on the right section
set-option -g status-right "\
#[fg=${FG},bg=default] ${LINUX} \
"

# Set max length of left and right section
set-option -g status-left-length 100
set-option -g status-right-length 100

# Style and set content for the inactive windows
set-option -g window-status-format "\
#[bg=${LIGHT_GRAY},fg=${BLACK}] #I \
#[fg=default, bg=${GRAY}] #W \
"

# Style and set content for the active windows
set-option -g window-status-current-format "\
#[bg=${MAUVE},fg=${BLACK}] #I \
#[fg=default, bg=${DARK_GRAY}] #W \
"

# Remove the separator between window list items, as we already have spacing
# "around" inactive items
set-option -g window-status-separator " "
