set -g status-bg                          "#121212"
set -gq @thm_bar_bg                       "#121212"

set -gq @thm_bg                           "#161616"
set -gq @thm_fg                           "#e6e6e6"

set -gq @thm_primary                      "#5f87af"
set -gq @thm_inverse_primary              "#121212"

set -gq @thm_surface_low                  "#1e1e1e"
set -gq @thm_surface                      "#262626"
set -gq @thm_surface_variant              "#303030"

set -gq @thm_outline                      "#666666"
set -gq @thm_text_variant                 "#bfbfbf"
