[general]
import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[colors]
primary = { background = "#000000" }

[env]
TERM = "xterm-256color"

[window]
padding = { x = 0, y = 0 }

[font]
normal = { family = "MesloLGS Nerd Font Mono"}

[terminal]
shell = {program = "/bin/zsh", args = ["-l"]}

[mouse]
hide_when_typing = true
