# gnome-dark Kitty Terminal Theme
# Based on GNOME color palette
 
background #1e222a
foreground #d9dce3
selection_background #5e81ac
selection_foreground #1e222a
cursor_text_color #1e222a
url_color #89a3c2
cursor #d9dce3
 
# normal
color0  #1e222a
color1  #c35b65
color2  #82ac5d
color3  #e4b558
color4  #5e81ac
color5  #b57daa
color6  #63a6a5
color7  #d9dce3
 
# bright
color8  #3a4150
color9  #d4878f
color10 #a0c082
color11 #eac985
color12 #89a3c2
color13 #c89dbf
color14 #83b9b8
color15 #f0f1f4
