$bg0 = rgb(0a1519)
$bg1 = rgb(0d181c)
$bg2 = rgb(1c272b)
$bg3 = rgb(2a3438)
$bg4 = rgb(455054)

$fg1 = rgb(d9d7d6)

$red    = rgb(c94f54)
$orange = rgb(d08570)
$yellow = rgb(d4bc7c)
$green  = rgb(6aa580)
$aqua   = rgb(67afc1)
$blue   = rgb(5a84bc)
$purple = rgb(bc83e3)

$grey0 = rgb(455054)

$hyprBorder = rgba(6aa580b3)
