$bg0 = rgb(0f1115)
$bg1 = rgb(1e222a)
$bg2 = rgb(242932)
$bg3 = rgb(333a47)
$bg4 = rgb(464f62)
$fg1 = rgb(d9dce3)
$red    = rgb(c35b65)
$orange = rgb(d08770)
$yellow = rgb(e4b558)
$green  = rgb(82ac5d)
$aqua   = rgb(63a6a5)
$blue   = rgb(5e81ac)
$purple = rgb(b57daa)
$grey0 = rgb(464f62)
$hyprBorder = rgba(5e81acb3)
